language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
sudo: false

install: ./gradlew assemble -x signArchives

script:
  - ./gradlew check -x signArchives

cache:
  directories:
  - "$HOME/.gradle/caches"
