# Site settings
title: Scassandra Server
email: chrisopher.batey@gmail.com
description: "making testing cassandra applications easy"
baseurl: "/scassandra-server"
url: "http://www.scassandra.org/server-stub"

# Build settings
markdown: redcarpet
permalink: pretty
